version: "3.9"
services:
  Web:
    image: "flask-app:1.0"
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: "true"
  jenkins:
    image: "flask-alpine:latest"
    ports:
      - "5001:5001"     